In [1]:
import cv2

In [30]:
#cap=cv2.VideoCapture("http://192.168.29.185:8080/video")
cap=cv2.VideoCapture(0)

In [31]:
status,photo=cap.read()

In [45]:
grayphoto = cv2.cvtColor(photo , cv2.COLOR_BGR2GRAY )

In [46]:
grayphoto

array([[42, 43, 43, ..., 48, 48, 50],
       [42, 43, 44, ..., 48, 48, 50],
       [42, 44, 44, ..., 49, 48, 50],
       ...,
       [30, 30, 30, ..., 36, 36, 37],
       [29, 29, 29, ..., 36, 36, 36],
       [30, 29, 28, ..., 36, 35, 36]], dtype=uint8)

In [47]:
cv2.imshow("Hi",grayphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [48]:
grayphoto.ndim

2

In [32]:
status

True

In [5]:
cv2.imshow("Hi",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [7]:
while True:
    status,photo=cap.read()
    cv2.imshow("Hi",photo)
    if cv2.waitKey(10)==13:
        break
cv2.destroyAllWindows()

In [8]:
photo

array([[[107, 135, 121],
        [110, 131, 124],
        [121, 135, 136],
        ...,
        [143, 155, 159],
        [145, 156, 160],
        [150, 161, 164]],

       [[113, 138, 127],
        [117, 137, 129],
        [121, 136, 132],
        ...,
        [150, 154, 159],
        [149, 153, 157],
        [155, 159, 163]],

       [[116, 139, 130],
        [118, 137, 129],
        [129, 144, 138],
        ...,
        [152, 153, 156],
        [155, 154, 157],
        [161, 160, 162]],

       ...,

       [[ 93, 104, 105],
        [ 84,  94,  94],
        [ 85,  94,  93],
        ...,
        [ 90, 109, 117],
        [ 89, 109, 114],
        [ 89, 109, 113]],

       [[ 92, 100, 102],
        [ 86,  94,  94],
        [ 87,  94,  93],
        ...,
        [ 92, 109, 117],
        [ 91, 108, 115],
        [ 91, 108, 115]],

       [[ 89,  98, 100],
        [ 87,  95,  95],
        [ 83,  90,  90],
        ...,
        [ 89, 107, 118],
        [ 90, 109, 118],
        [ 90, 109, 118]]

In [9]:
photo.ndim

3

In [22]:
photo[10,30]

array([146, 151, 150], dtype=uint8)

In [23]:
photo[30,10,2]

145

In [24]:
photo[30,10,0:2]=0

In [25]:
photo[30,10]

array([  0,   0, 145], dtype=uint8)

In [33]:
photo[: ,: , 0:2]=0

In [34]:
photo

array([[[  0,   0, 139],
        [  0,   0, 144],
        [  0,   0, 144],
        ...,
        [  0,   0, 161],
        [  0,   0, 162],
        [  0,   0, 167]],

       [[  0,   0, 140],
        [  0,   0, 144],
        [  0,   0, 146],
        ...,
        [  0,   0, 161],
        [  0,   0, 162],
        [  0,   0, 167]],

       [[  0,   0, 141],
        [  0,   0, 146],
        [  0,   0, 146],
        ...,
        [  0,   0, 163],
        [  0,   0, 162],
        [  0,   0, 166]],

       ...,

       [[  0,   0,  99],
        [  0,   0,  99],
        [  0,   0, 101],
        ...,
        [  0,   0, 121],
        [  0,   0, 122],
        [  0,   0, 124]],

       [[  0,   0,  98],
        [  0,   0,  96],
        [  0,   0,  97],
        ...,
        [  0,   0, 120],
        [  0,   0, 119],
        [  0,   0, 119]],

       [[  0,   0,  99],
        [  0,   0,  97],
        [  0,   0,  95],
        ...,
        [  0,   0, 120],
        [  0,   0, 118],
        [  0,   0, 119]]

In [42]:
cv2.imshow("Hi",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [43]:
photo[: ,: , 0]+50

array([[50, 50, 50, ..., 50, 50, 50],
       [50, 50, 50, ..., 50, 50, 50],
       [50, 50, 50, ..., 50, 50, 50],
       ...,
       [50, 50, 50, ..., 50, 50, 50],
       [50, 50, 50, ..., 50, 50, 50],
       [50, 50, 50, ..., 50, 50, 50]], dtype=uint8)

In [10]:
import numpy

In [11]:
a=numpy.array([1,2,3,4])

In [12]:
a.ndim

1

In [13]:
a[1:4]

array([2, 3, 4])

In [14]:
a[1:4]=100

In [15]:
a

array([  1, 100, 100, 100])

In [16]:
b=numpy.array([
    [1,10,100],
    [2,20,200],
    [3,30,300],
    [4,40,400]
])

In [17]:
b.ndim

2

In [18]:
b.shape

(4, 3)

In [20]:
b[1:3,1:3]=5

In [21]:
b

array([[  1,  10, 100],
       [  2,   5,   5],
       [  3,   5,   5],
       [  4,  40, 400]])