In [6]:
import cv2

In [7]:
cap = cv2.VideoCapture(0)

In [8]:
status, photo=cap.read()

In [9]:
x=5

In [10]:
y=10

In [11]:
a,b=x,y   #multi value assignment in single statement

In [12]:
a


5

In [13]:
b

10

In [14]:
status

True

In [15]:
 cv2.imwrite("pulkit.png",photo)

True

In [16]:
cv2.imshow("my photo",photo)
#cv2.waitKey()
if cv2.waitKey()==27:
    cv2.destroyAllWindows()

In [17]:
photo

array([[[16, 10,  4],
        [17, 11,  5],
        [17, 11,  5],
        ...,
        [38, 18,  2],
        [32, 18,  1],
        [31, 18,  1]],

       [[16, 10,  4],
        [17, 11,  5],
        [17, 11,  5],
        ...,
        [38, 18,  2],
        [34, 18,  1],
        [34, 18,  1]],

       [[16, 10,  4],
        [17, 11,  5],
        [17, 11,  5],
        ...,
        [39, 18,  2],
        [38, 17,  1],
        [38, 17,  1]],

       ...,

       [[25, 12,  2],
        [25, 11,  2],
        [25, 11,  3],
        ...,
        [15,  8,  2],
        [15,  8,  2],
        [15,  8,  2]],

       [[25, 11,  3],
        [25, 11,  3],
        [25, 11,  3],
        ...,
        [15,  8,  2],
        [15,  8,  2],
        [15,  8,  2]],

       [[25, 11,  3],
        [25, 11,  3],
        [25, 11,  3],
        ...,
        [15,  8,  2],
        [15,  8,  2],
        [15,  8,  2]]], dtype=uint8)

In [18]:
type(photo)

numpy.ndarray

In [19]:
photo.shape

(480, 640, 3)

In [20]:
photo.ndim

3

In [21]:
a=[1,2,3]
a[1]

2

In [22]:
photo[100]

array([[15,  9,  5],
       [12,  8,  3],
       [11,  8,  3],
       ...,
       [36, 14,  2],
       [36, 14,  2],
       [36, 14,  2]], dtype=uint8)

In [23]:
photo[100]=[0,255,0]

In [24]:
photo[200]=[0,0,255]

In [25]:
newphoto=photo[100:250,200:450]

In [26]:
photo[0:150,0:250]=photo[100:250,200:450]

In [27]:
cv2.imshow("my photo",newphoto)
cv2.waitKey()
cv2.destroyAllWindows()

In [28]:
B, G, R=cv2.split(photo)

In [29]:
B

array([[ 0,  0,  0, ..., 38, 32, 31],
       [21, 21, 21, ..., 38, 34, 34],
       [21, 21, 21, ..., 39, 38, 38],
       ...,
       [25, 25, 25, ..., 15, 15, 15],
       [25, 25, 25, ..., 15, 15, 15],
       [25, 25, 25, ..., 15, 15, 15]], dtype=uint8)

In [30]:
cv2.imshow("my photo",B)
cv2.waitKey()
cv2.destroyAllWindows()

In [31]:
a=[1,2,3,4,5,6]

In [32]:
a[3:6]

[4, 5, 6]

In [33]:
a[0:3]=a[3:6]

In [34]:
a

[4, 5, 6, 4, 5, 6]

In [35]:
#while True:
#   status, photo=cap.read()
#   cv2.imshow("my photo",photo)
#   cv2.waitKey(100)
#cv2.destroyAllWindows()

In [46]:
while True:
    status, photo=cap.read()
    #newphoto=photo[100:250,200:450]
    #photo[0:150,0:250]=photo[100:250,200:450]
    photo[:,:,1]=+50
    cv2.imshow("my photo",photo)
    if cv2.waitKey(10)==13:
        break
cv2.destroyAllWindows()

In [37]:
a=[1,2,3,4,5,6]
a[0]+=3

In [38]:
a

[4, 2, 3, 4, 5, 6]

In [39]:
a[0]=a[3:6]

In [40]:
a

[[4, 5, 6], 2, 3, 4, 5, 6]

In [41]:
photo[:,:,2]=+50

In [44]:
cv2.imshow("my photo",photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [47]:
cap.release()