In [2]:
import pandas

In [3]:
dataset = pandas.read_csv("xyzcollege-cs-4thyear - Sheet1.csv")

In [4]:
dataset

name  hrs  marks
0  Rahul    4     40
1   Eric    6     60
2    Tom    8     80
3   Yash    3     30

In [5]:
y=dataset["marks"]

In [6]:
y

0    40
1    60
2    80
3    30
Name: marks, dtype: int64

In [7]:
x=dataset["hrs"]

In [8]:
x

0    4
1    6
2    8
3    3
Name: hrs, dtype: int64

In [9]:
from sklearn.linear_model import LinearRegression

In [10]:
#y=cx
model = LinearRegression()

In [11]:
model.fit(x,y)

ValueError: Expected 2D array, got 1D array instead:
array=[4 6 8 3].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [14]:
type(x)

pandas.core.series.Series

In [12]:
x.values

array([4, 6, 8, 3], dtype=int64)

In [13]:
type(x.values)

numpy.ndarray

In [15]:
x.values.shape

(4,)

In [17]:
X=x.values.reshape(4,1)

In [18]:
X

array([[4],
       [6],
       [8],
       [3]], dtype=int64)

In [19]:
X.shape

(4, 1)

In [20]:
X.ndim

2

In [21]:
#c=10
#y=10x
model.fit(X,y)

LinearRegression()

In [23]:
model.predict([[ 5 ]])

array([50.])

In [24]:
model.coef_

array([10.])

In [25]:
import joblib

In [26]:
joblib.dump(model,"mymarks.model")

['mymarks.model']